# Generated by Django 5.2.3 on 2025-06-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="apartament_number",
            new_name="apartment_number",
        ),
    ]
