# Generated by Django 5.2.3 on 2025-07-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_apartament_number_user_apartment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apartment_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Индекс"),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, max_length=100, verbose_name="Улица"),
        ),
    ]
