# Generated by Django 5.2.3 on 2025-07-02 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterField(
            model_name="order",
            name="apartment_number",
            field=models.CharField(max_length=10, verbose_name="Номер квартиры"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="house_number",
            field=models.CharField(max_length=10, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="order",
            name="middle_name",
            field=models.CharField(max_length=30, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                default="В ожидании",
                max_length=40,
                verbose_name="Номер отслеживания",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
